### PR TITLE
Multi network support

### LINKED ISSUE #90: No camera show's up
```python
from blinkpy import blinkpy

blink = blinkpy.Blink(username='XXXX@gmail.com', password='XXXX')
blink.start()

for name, camera in blink.sync.cameras.items():
    print(name)                   # Name of the camera
    print(camera.attributes)      # Print available attributes of camera
```

This code doesn't show up any camera. 

Cameras do show up in the app

### PR DESCRIPTION
**Pull request by fronzbot**
## Description:
Grabs the network information from the login response.  I'm not 100% sure that this will solve the problem, but it seems reasonable.

**Related issue (if applicable):** fixes #90 

## Checklist:
- [x] Local tests with `tox` run successfully **PR cannot be meged unless tests pass**
- [x] Tests added to verify new code works

### CODE REVIEW

**Comment by dib0** [comment]
Hi.

I tried to test, but in both cases got an error. It should connect to an European server. I'm not sure if this is the "No camera's show up" error or the "Can't connect to the right server error"

``
redacted:~/Downloads/blinkpy $ python3
Python 3.6.3 (default, Oct  8 2017, 19:39:00) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from blinkpy import blinkpy
>>> b = blinkpy.Blink()
>>> b.start()
Username:me@domain.com
Password:
Could not extract clip info from camera Camera1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/redacted/Downloads/blinkpy/blinkpy/blinkpy.py", line 79, in start
    self.sync.start()
  File "/home/redacted/Downloads/blinkpy/blinkpy/sync_module.py", line 100, in start
    self.cameras[name].update(camera_config, force_cache=True)
  File "/home/redacted/Downloads/blinkpy/blinkpy/camera.py", line 146, in update
    json=False)
  File "/home/redacted/Downloads/blinkpy/blinkpy/api.py", line 148, in http_get
    reqtype='get', stream=stream, json_resp=json)
  File "/home/redacted/Downloads/blinkpy/blinkpy/helpers/util.py", line 47, in http_req
    prepped = req.prepare()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 263, in prepare
    hooks=self.hooks,
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 309, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 383, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
>>> exit()
redacted:~/Downloads/blinkpy $ git checkout multi-network-support
Branch multi-network-support set up to track remote branch multi-network-support from origin.
Switched to a new branch 'multi-network-support'
redacted:~/Downloads/blinkpy $ python3
Python 3.6.3 (default, Oct  8 2017, 19:39:00) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from blinkpy import blinkpy
>>> b = blinkpy.Blink()
>>> b.start()
Username:me@domain.com
Password:
Could not extract clip info from camera Camera1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/redacted/Downloads/blinkpy/blinkpy/blinkpy.py", line 80, in start
    self.sync.start()
  File "/home/redacted/Downloads/blinkpy/blinkpy/sync_module.py", line 100, in start
    self.cameras[name].update(camera_config, force_cache=True)
  File "/home/redacted/Downloads/blinkpy/blinkpy/camera.py", line 146, in update
    json=False)
  File "/home/redacted/Downloads/blinkpy/blinkpy/api.py", line 148, in http_get
    reqtype='get', stream=stream, json_resp=json)
  File "/home/redacted/Downloads/blinkpy/blinkpy/helpers/util.py", line 47, in http_req
    prepped = req.prepare()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 263, in prepare
    hooks=self.hooks,
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 309, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 383, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by dib0** [comment]
Oh... didn't read through.

If I enter print(b.networks) I get the following result (redacted, values are the right ID and name):
{'xxx': {'name': 'mynetworkname', 'onboarded': True}}

**Comment by dib0** [comment]
The loop (on the multi-network-support branch) gives the following result:
name: CameraRedacted
network: xxx
thumb: https://rest.prde.immedia-semi.com/media/production/account/xxx/network/yyy/camera/zzz/blabla.jpg
voltage: None
name: None
network: None
thumb: None
voltage: None
name: None
network: None
thumb: None
voltage: None

I have 3 camera's on this network. I'll trigger some video recording in a minute to test if the show up.

**Comment by dgomes** [comment]
Something fishy still:


name: Blink 1
network: 31911
thumb: https://rest.prde.immedia-semi.com/media/production/account/<redacted>/network/31911/camera/92599/clip_9iTtJ6HU_2018_10_15__18_25PM.jpg
**voltage: https://rest.prde.immedia-semi.com/media/production/account/<redacted>/network/31911/camera/92599/clip_bfssvApC_2018_10_10__16_46PM.mp4**
name: Blink 2
network: 31911
thumb: https://rest.prde.immedia-semi.com/media/production/account/<redacted>/network/31911/camera/124022/clip_h8mHvdW1_2018_10_13__19_18PM.jpg
voltage: None
name: Blink 3
network: 31911
thumb: https://rest.prde.immedia-semi.com/media/production/account/<redacted>/network/31911/camera/124027/clip_kYLvGAUE_2018_10_13__19_18PM.jpg
voltage: None

That voltage has a thumb :)

**Comment by dib0** [comment]
I did a retest. Seems to be working fine now!

Thanks! 


________________________________

**Pull request merged**
