### PR TITLE
Add support for Blink Minis

### LINKED ISSUE #224: Support for Mini
**Is your feature request related to a problem? Please describe.**
I tried the Home Assistant integration, but don't get any devices, so I don't think the mini is supported yet.

**Describe the solution you'd like**
Support for the Blink mini.

**Additional context**
https://www.amazon.com/stores/page/C5DECBBE-4F56-4C36-B933-E62144578691?channel=productmini

### PR DESCRIPTION
**Pull request by fronzbot**
## Description:
Adds rough support for blink minis.  Untested (as I don't own any) so will not merge until someone is able to test and verify.  To help out:

### Clone this repo and checkout the PR
Fork this repo in github and then do the following:
```bash
git clone https://github.com/<YOUR_GIT_USERNAME>/blinkpy.git
cd blinkpy
git remote add upstream https://github.com/fronzbot/blinkpy.git
git fetch upstream
git checkout -b add-minis upstream/add-minis
```

### Run the following code to start up your blink instance
Will prompt for username, password, and possibly 2FA key
```python
from blinkpy.blinkpy import Blink
blink = Blink()
blink.start()
```

### ~Check that homescreen property contains cameras~
No longer needed, thank you!
```python
print(blink.homescreen)
```

### Check that cameras are in sync and camera dictionaries
```python
print("Sync Modules:")
for name in blink.sync:
    print(name)
print("Cameras:")
for name in blink.cameras:
    print(name)
```

### Verify thumbnail is correct (returns a url)
```python
print(blink.cameras["NAME OF MINI CAMERA"].thumbnail)
```

### Verify arming/disarming cameras works
First, make sure the camera is disarmed in the blink app.  Then run the following code and wait (up to 60s) to see the state change in the app (usually closer to 5s/10s, but Blink can be slow...)
```python
blink.refresh()
# Following print statement should print 'False'
print(blink.sync["NAME OF MINI CAMERA"].arm)
blink.sync["NAME OF MINI CAMERA"].arm = True
```

Now wait 60s or so and double check that you can read the status back after a refresh (print statement should print 'True')
```python
blink.refresh()
print(blink.sync["NAME OF MINI CAMERA"].arm)
```

### Report back results
Please comment on this PR with your results if you run through theses tests.  If you run into any problems, please let me know with as much detail as you can provide so I can fix it!

**Related issue (if applicable):** fixes #224 

## Checklist:
- [x] Local tests with `tox` run successfully **PR cannot be meged unless tests pass**
- [ ] Changes tested locally to ensure platform still works as intended
- [x] Tests added to verify new code works

### CODE REVIEW

**Comment by HughAndersonNUS** [comment]
Hi - I tried out this, on my system with 4 other cameras, on two networks, and the Blink Mini:
`Hughs-MacBook-4:blinkpy hugh$ python3
Python 3.7.4 (default, Oct 10 2019, 08:46:34) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from blinkpy.blinkpy import Blink
>>> blink = Blink()
>>> blink.start()
Username:hugh.anderson@acm.org
Password:
Enter code sent to XXXX@YYYY: XXXXXXX
True
>>> print(blink.homescreen)
`
`{'account': {'id': ID-1, 'email_verified': True, 'email_verification_required': False}, 'networks': [{'id': NW-1, 'created_at': '2018-01-05T07:29:52+00:00', 'updated_at': '2020-06-06T20:10:47+00:00', 'name': 'DBInside', 'time_zone': 'Pacific/Auckland', 'dst': True, 'armed': False, 'lv_save': False}, {'id': NW-2, 'created_at': '2018-01-06T10:04:58+00:00', 'updated_at': '2020-05-31T19:52:51+00:00', 'name': 'DB', 'time_zone': 'Pacific/Auckland', 'dst': True, 'armed': True, 'lv_save': False}, {'id': 272250, 'created_at': '2020-05-20T06:21:48+00:00', 'updated_at': '2020-06-06T20:17:40+00:00', 'name': 'Home', 'time_zone': 'Pacific/Auckland', 'dst': True, 'armed': False, 'lv_save': False}], 'sync_modules': [{'id': 439557, 'created_at': '2018-01-05T07:31:22+00:00', 'updated_at': '2020-06-06T20:55:45+00:00', 'onboarded': True, 'status': 'offline', 'name': 'My Blink Sync Module', 'serial': '283010330', 'fw_version': '2.13.18', 'last_hb': '2020-06-06T20:10:58+00:00', 'wifi_strength': 1, 'network_id': NW-1, 'enable_temp_alerts': True}, {'id': 439756, 'created_at': '2018-01-06T10:05:15+00:00', 'updated_at': '2020-06-09T04:55:23+00:00', 'onboarded': True, 'status': 'online', 'name': 'My Blink Sync Module', 'serial': '210312939', 'fw_version': '2.13.18', 'last_hb': '2020-06-09T05:18:45+00:00', 'wifi_strength': 2, 'network_id': NW-2, 'enable_temp_alerts': True}], 'cameras': [{'id': CAM-1, 'created_at': '2018-01-05T07:36:59+00:00', 'updated_at': '2020-06-06T20:10:50+00:00', 'name': 'Frontdoor-DH', 'serial': '123011606', 'fw_version': '2.151', 'type': 'white', 'enabled': True, 'thumbnail': '/media/production/account/ID-1/network/NW-1/camera/CAM-1/clip_gDp_n13V_2020_05_25__05_40AM', 'status': 'done', 'battery': 'ok', 'usage_rate': False, 'network_id': NW-1, 'issues': [], 'signals': {'lfr': 4, 'wifi': 5, 'temp': 43, 'battery': 3}}, {'id': CAM-2, 'created_at': '2018-01-05T07:39:52+00:00', 'updated_at': '2020-06-06T20:10:51+00:00', 'name': 'Livingarea-DJ', 'serial': '163010045', 'fw_version': '2.151', 'type': 'white', 'enabled': True, 'thumbnail': '/media/production/account/ID-1/network/NW-1/camera/CAM-2/clip_Na_6TECv_2020_06_04__22_12PM', 'status': 'done', 'battery': 'ok', 'usage_rate': False, 'network_id': NW-1, 'issues': [], 'signals': {'lfr': 5, 'wifi': 5, 'temp': 44, 'battery': 3}}, {'id': CAM-3, 'created_at': '2018-01-06T10:08:42+00:00', 'updated_at': '2020-06-09T05:08:44+00:00', 'name': 'Driveway-DF', 'serial': '630049981', 'fw_version': '2.151', 'type': 'xt', 'enabled': True, 'thumbnail': '/media/production/account/ID-1/network/NW-2/camera/CAM-3/clip_5FK7kfUV_2020_06_09__03_31AM', 'status': 'done', 'battery': 'ok', 'usage_rate': False, 'network_id': NW-2, 'issues': [], 'signals': {'lfr': 5, 'wifi': 1, 'temp': 42, 'battery': 3}}, {'id': CAM-4, 'created_at': '2018-01-06T10:10:51+00:00', 'updated_at': '2020-06-09T05:08:45+00:00', 'name': 'Kitchen-DE', 'serial': '640050483', 'fw_version': '2.151', 'type': 'xt', 'enabled': True, 'thumbnail': '/media/production/account/ID-1/network/NW-2/camera/CAM-4/clip_17rsJ8Zs_2020_06_09__03_31AM', 'status': 'done', 'battery': 'ok', 'usage_rate': False, 'network_id': NW-2, 'issues': [], 'signals': {'lfr': 5, 'wifi': 1, 'temp': 42, 'battery': 3}}], 'sirens': [], 'chimes': [], 'video_stats': {'storage': 1, 'auto_delete_days': 0}, 'doorbell_buttons': [], 'owls': [{'id': OWL-ID-1, 'created_at': '2020-05-20T06:22:10+00:00', 'updated_at': '2020-06-09T04:58:09+00:00', 'name': 'Living Room', 'type': 'owl', 'onboarded': True, 'serial': 'G8T1900000314G7C', 'fw_version': '9.63', 'enabled': True, 'thumbnail': '/media/production/account/ID-1/network/NW-OWL/owl/OWL-ID-1/thumbnail/fw_9.63__BmdcL7LZ_2020_06_09__03_29AM', 'status': 'online', 'network_id': NW-OWL}], 'app_updates': {'message': 'An app update is required', 'code': 105, 'update_available': True, 'update_required': True}, 'device_limits': {'total_devices': 20, 'owl': 10, 'camera': 10, 'siren': 5, 'doorbell_button': 2, 'chime': 5}, 'whats_new': {'updated_at': 20200415, 'url': 'https://blinkforhome.com/blogs/updates'}}
`

So - from there on things dont seem to work. The blink mini does not have a "name" and "network" like the others, but there does appear to be information about it in the OWL tags above.
I hope I have deleted everything that is important up there :)

`>>> print("Sync Modules:")
Sync Modules:
>>> for name in blink.sync:
...     print(name)
... 
DBInside
DB
Living Room
>>> print("Cameras:")
Cameras:
>>> for name in blink.cameras:
...     print(name)
... 
Driveway-DF
Kitchen-DE`

So I get two cameras in the DB sync module. The other one is offline at the moment, and no cameras from the "Living Room" Blink Mini  (virtual) sync module.

CHeers Hugh

**Comment by HughAndersonNUS** [comment]
Hi Kevin, looking at the value returned by blink.homescreen, there is an entry for the Blink Mini in the networks section:
`  'networks': [`
`            {'id': NW-1, .....  },`
`            {'id': NW-2,  ...},`
`            {'id': NW-OWL, 'created_at': '2020-05-20T06:21:48+00:00', 'updated_at': '2020-06-06T20:17:40+00:00', 'name': 'Home', 'time_zone': 'Pacific/Auckland', 'dst': True, 'armed': False, 'lv_save': False}],`


And, NO entry in the cameras section, but the new 'Owls" section has the details:

`  'owls': [{'id': OWL-ID-1,`
`            'created_at': '2020-05-20T06:22:10+00:00',`
`            'updated_at': '2020-06-09T04:58:09+00:00',`
`            'name': 'Living Room',`
`            'type': 'owl',`
`            'onboarded': True,`
`            'serial': 'ZZZZZZZZ',`
`            'fw_version': '9.63',`
`            'enabled': True,`
`            'thumbnail': '/media/production/account/ID-1/network/NW-OWL/owl/OWL-ID-1/thumbnail/fw_9.63__BmdcL7LZ_2020_06_09__03_29AM',`
`            'status': 'online',`
`            'network_id': NW-OWL}],`


Cheers Hugh

**Comment by chbndrhnns** [comment]
This is how it looks for my mini:

```
>>> print(b.homescreen)
{'account': {'id': x, 'email_verified': True, 'email_verification_required': True}, 'networks': [{'id': x, 'created_at': '2020-04-20T17:13:48+00:00', 'updated_at': '2020-06-03T17:31:16+00:00', 'name': 'Home', 'time_zone': 'Europe/Berlin', 'dst': True, 'armed': False, 'lv_save': False}], 'sync_modules': [], 'cameras': [], 'sirens': [], 'chimes': [], 'video_stats': {'storage': 1, 'auto_delete_days': 14}, 'doorbell_buttons': [], 'owls': [{'id': 280, 'created_at': '2020-04-20T17:14:36+00:00', 'updated_at': '2020-06-07T18:36:18+00:00', 'name': 'G8T1-9400-0135-1HVM', 'type': 'owl', 'onboarded': True, 'serial': 'x', 'fw_version': '9.63', 'enabled': True, 'thumbnail': '/media/e002/account/x/network/x/owl/280/thumbnail/x', 'status': 'online', 'network_id': x}], 'app_updates': {'message': 'An app update is required', 'code': 105, 'update_available': True, 'update_required': True}, 'device_limits': {'total_devices': 20, 'owl': 10, 'camera': 10, 'siren': 5, 'doorbell_button': 2, 'chime': 5}, 'whats_new': {'updated_at': 20200416, 'url': 'https://blinkforhome.com/blogs/updates'}}
>
```

```
>>> print(b.cameras)
{}
```

**Comment by benleb** [comment]
```python
>>> pprint(blink.homescreen)
{'account': {'email_verification_required': True,
             'email_verified': True,
             'id': <account id>},
 'app_updates': {'code': 105,
                 'message': 'An app update is required',
                 'update_available': True,
                 'update_required': True},
 'cameras': [],
 'chimes': [],
 'device_limits': {'camera': 10,
                   'chime': 5,
                   'doorbell_button': 2,
                   'owl': 10,
                   'siren': 5,
                   'total_devices': 20},
 'doorbell_buttons': [],
 'networks': [{'armed': False,
               'created_at': '2020-05-13T11:11:21+00:00',
               'dst': True,
               'id': <network id>,
               'lv_save': False,
               'name': 'SyBe',
               'time_zone': 'Europe/Berlin',
               'updated_at': '2020-05-29T10:30:58+00:00'}],
 'owls': [{'created_at': '2020-05-13T11:11:47+00:00',
           'enabled': True,
           'fw_version': '9.63',
           'id': <owl id>,
           'name': 'blimi',
           'network_id': <network id>,
           'onboarded': True,
           'serial': 'G8T19400013513TS',
           'status': 'online',
           'thumbnail': '/media/e002/account/<account id>/network/<network id>/owl/<owl id>/thumbnail/fw_9.63__SseVTsm1_2020_06_08__15_02PM',
           'type': 'owl',
           'updated_at': '2020-06-08T23:28:19+00:00'}],
 'sirens': [],
 'sync_modules': [],
 'video_stats': {'auto_delete_days': 30, 'storage': 0},
 'whats_new': {'updated_at': 20200416,
               'url': 'https://blinkforhome.com/blogs/updates'}}
>>> print("Sync Modules:")
Sync Modules:
>>> for name in blink.sync:
...     print(name)
...
blimi
>>> print("Cameras:")
Cameras:
>>> for name in blink.cameras:
...     print(name)
...
>>>
```

**Comment by benleb** [comment]
seems like before... 

```python
{'account': {'email_verification_required': True,
             'email_verified': True,
             'id': <account id>},
 'app_updates': {'code': 105,
                 'message': 'An app update is required',
                 'update_available': True,
                 'update_required': True},
 'cameras': [],
 'chimes': [],
 'device_limits': {'camera': 10,
                   'chime': 5,
                   'doorbell_button': 2,
                   'owl': 10,
                   'siren': 5,
                   'total_devices': 20},
 'doorbell_buttons': [],
 'networks': [{'armed': False,
               'created_at': '2020-05-13T11:11:21+00:00',
               'dst': True,
               'id': <network id>,
               'lv_save': False,
               'name': '<network name>',
               'time_zone': 'Europe/Berlin',
               'updated_at': '2020-05-29T10:30:58+00:00'}],
 'owls': [{'created_at': '2020-05-13T11:11:47+00:00',
           'enabled': True,
           'fw_version': '9.63',
           'id': <owl id>,
           'name': 'blimi',
           'network_id': <network id>,
           'onboarded': True,
           'serial': 'G8T19400013513TS',
           'status': 'online',
           'thumbnail': '/media/e002/account/<account id>/network/<network id>/owl/<owl id>/thumbnail/fw_9.63__SseVTsm1_2020_06_08__15_02PM',
           'type': 'owl',
           'updated_at': '2020-06-08T23:28:19+00:00'}],
 'sirens': [],
 'sync_modules': [],
 'video_stats': {'auto_delete_days': 30, 'storage': 0},
 'whats_new': {'updated_at': 20200416,
               'url': 'https://blinkforhome.com/blogs/updates'}}

Sync Modules:
  blimi

Cameras:

Traceback (most recent call last):
  File "dbg.py", line 25, in <module>
    print(blink.cameras[owl_name].thumbnail)
KeyError: 'blimi'
```

**Comment by benleb** [comment]
```bash
python3 owlinfo.py <owl name>
```

```python
import sys

from pprint import pprint

from blinkpy.blinkpy import Blink


owl_name = sys.argv[1] if len(sys.argv) >= 2 else "blimi"


blink = Blink()
blink.start()

pprint(blink.homescreen)
print()

print("Sync Modules:")
for name in blink.sync:
    print(f"  {name}")
print()

print("Cameras:")
for name in blink.cameras:
    print(f"  {name}")
print()

try:
    print(f"{blink.cameras[owl_name].thumbnail = }")
except Exception as error:
    print(error)
print()

try:
    blink.refresh()
    print(f"{blink.sync[owl_name].arm = }")
except Exception as error:
    print(error)
print()

try:
    blink.sync[owl_name].arm = True
except Exception as error:
    print(error)
print()

try:
    blink.refresh()
    print(f"{blink.sync[owl_name].arm = }")
except Exception as error:
    print(error)
print()
```

**Comment by benleb** [comment]
:D we are on the right way...

```python
{'account': {'email_verification_required': True,
             'email_verified': True,
             'id': <account id>},
 'app_updates': {'code': 105,
                 'message': 'An app update is required',
                 'update_available': True,
                 'update_required': True},
 'cameras': [],
 'chimes': [],
 'device_limits': {'camera': 10,
                   'chime': 5,
                   'doorbell_button': 2,
                   'owl': 10,
                   'siren': 5,
                   'total_devices': 20},
 'doorbell_buttons': [],
 'networks': [{'armed': False,
               'created_at': '2020-05-13T11:11:21+00:00',
               'dst': True,
               'id': <network id>,
               'lv_save': False,
               'name': '<network name>',
               'time_zone': 'Europe/Berlin',
               'updated_at': '2020-05-29T10:30:58+00:00'}],
 'owls': [{'created_at': '2020-05-13T11:11:47+00:00',
           'enabled': True,
           'fw_version': '9.63',
           'id': <owl id>,
           'name': 'blimi',
           'network_id': <network id>,
           'onboarded': True,
           'serial': 'G8T19400013513TS',
           'status': 'online',
           'thumbnail': '/media/e002/account/<account id>/network/<network id>/owl/<owl id>/thumbnail/fw_9.63__SseVTsm1_2020_06_08__15_02PM',
           'type': 'owl',
           'updated_at': '2020-06-08T23:28:19+00:00'}],
 'sirens': [],
 'sync_modules': [],
 'video_stats': {'auto_delete_days': 30, 'storage': 0},
 'whats_new': {'updated_at': 20200416,
               'url': 'https://blinkforhome.com/blogs/updates'}}

Sync Modules:
  blimi

Cameras:
  blimi

blink.cameras[owl_name].thumbnail = 'https://rest-e002.immedia-semi.com/media/e002/account/<account id>/network/<network id>/owl/<owl id>/thumbnail/fw_9.63__SseVTsm1_2020_06_08__15_02PM.jpg'

blink.sync[owl_name].arm = True

Connection error. Endpoint https://rest-e002.immedia-semi.com/network/<network id>/camera/<owl id>/enable possibly down or throttled. 404: Not Found

sleeping for 60s now

blink.sync[owl_name].arm = True
```

**Comment by benleb** [comment]
POST (empty payload) to
`https://rest-e002.immedia-semi.com/api/v1/accounts/<account id>/networks/<network id>/state/arm`
`https://rest-e002.immedia-semi.com/api/v1/accounts/<account id>/networks/<network id>/state/disarm`
to arm/disarm

```python
Connection error. Endpoint https://rest-e002.immedia-semi.com/network/<network id>/camera/<owl id>/thumbnail possibly down or throttled. 404: Not Found
thumbnail = None

blink.cameras[owl_name].thumbnail = 'https://rest-e002.immedia-semi.com/media/e002/account/<account id>/network/<network id>/owl/<owl id>/thumbnail/fw_9.63__SseVTsm1_2020_06_08__15_02PM.jpg'
```

downloaded picture is valid :)

**Comment by benleb** [comment]
works :) 

```python
...
thumbnail = {'id': 11328080, 'network_id': <network id>, 'command': 'thumbnail', 'state': 'new'}
...
```

nice job 👍

**Comment by chbndrhnns** [comment]
I get this message when trying to disarm my mini:

```
>>> blink.sync["entrance"].arm = False
Connection error. Endpoint https://rest-e002.immedia-semi.com/network/x/camera/x/disable possibly down or throttled. 404: Not Found
```

**Pull request merged**
